language: r
r:
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - release
  - devel

sudo: false

cache: packages

r_packages:
  - covr

branches:
  only:
    - master
    - development
    - rc

after_success:
  - Rscript covr.R
